# Makefile

# Hedef dosya adı
TARGET = dapie

# Python betik dosyası
PYTHON_SCRIPT = dapie.py

# PyInstaller komutu
PYINSTALLER_CMD = pyinstaller

# PyInstaller parametreleri
PYINSTALLER_FLAGS = --onefile --name=$(TARGET) --noconsole

# Derleme hedefi
all: $(TARGET)

$(TARGET):
    @echo "Gereklilikleri yükleme..."
    @pip install -r requirements.txt
    @echo "Derleme..."
    $(PYINSTALLER_CMD) $(PYINSTALLER_FLAGS) $(PYTHON_SCRIPT)

clean:
    rm -rf build/ dist/ $(TARGET).spec

.PHONY: clean
